### ISSUE TITLE
Python Errno 8 Exec format error

### ISSUE THREAD

**Issue by fonikz** [DarkMatterCore/wad2bin#29]
I'm getting this when I hit Run in the GUI:

> /usr/lib/python3.10/subprocess.py:955: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdin = io.open(p2cwrite, 'wb', bufsize)
/usr/lib/python3.10/subprocess.py:961: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
Exception in thread Thread-2 (execute_script):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Desktop/wad2bin-gui-linux-x86_64/gui.py", line 566, in execute_script
    p = subprocess.Popen(args,
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/user/Desktop/wad2bin-gui-linux-x86_64/wad2bin'

**Comment by fonikz** [comment]
DERP I downloaded the ARM file instead of x86. Sorry.
